- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Install aptitude, for better package management
    apt:
      name: aptitude
      state: latest
      update_cache: true

  - name: Update package cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Upgrade all packages
    apt: upgrade=dist force_apt_get=yes

  - name: Install required system packages
    apt:
      pkg:
        - git
        - fish
        - vim
        - ranger
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
#        - python3-dev
        - virtualenv
        - python3-setuptools
      state: latest

