##################################################################################################
## Tailscale
##    As per https://tailscale.com/download/linux/ubuntu-2004
##################################################################################################
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Add Tailscale GPG apt Key
    apt_key:
      id: 2596A99EAAB33821893C0A79458CA832957F5868
      url: https://pkgs.tailscale.com/stable/ubuntu/focal.gpg
      state: present
      keyring: /etc/apt/trusted.gpg.d/tailscale-archive-keyring.gpg

  - name: Add Tailscale Repository
    apt_repository:
      repo: deb [signed-by=/etc/apt/trusted.gpg.d/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu focal main
      state: present

  - name: Install Tailscale
    apt:
      name:
        - tailscale
      state: latest
      update_cache: true
